dist: xenial
language: csharp
solution: eform-eform-BaseCustomer-base/Microting.eFormBaseCustomerBase.sln
mono: none
dotnet: 3.1
addons:
  mariadb: '10.5'
script:
  - sudo mysql -e 'ALTER USER root@localhost IDENTIFIED VIA mysql_native_password'
  - dotnet restore
  - dotnet build Microting.eFormBaseCustomerBase.sln
  - dotnet test -v n Microting.eFormBaseCustomerBase.Unit.Tests/Microting.eFormBaseCustomerBase.Unit.Tests.csproj
  - dotnet test -v n Microting.eFormBaseCustomerBase.Integration.Tests/Microting.eFormBaseCustomerBase.Integration.Tests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.eFormBaseCustomerBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-BaseCustomer-base/artifacts/Microting.eFormBaseCustomerBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
